version: "3.8"

services:
  app:
    build: .
    container_name: devtools-hub
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - production.env
    networks:
      - devtools-network

  nginx:
    image: nginx:alpine
    container_name: devtools-nginx
    restart: unless-stopped
    # Ports supprimés - nginx externe gère maintenant le trafic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - devtools-network
    # Configuration pour la production
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d

networks:
  devtools-network:
    driver: bridge
