version: "3.8"

services:
  app:
    build: .
    container_name: devtools-hub
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - production.env
    networks:
      - devtools-network

  nginx:
    image: nginx:alpine
    container_name: devtools-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - devtools-network

networks:
  devtools-network:
    driver: bridge
